name: pulsing_button
version: 0.0.6
description: A fully customizable pulsing button for Flutter. Works the same way RawMaterialButton works.
repository: "https://github.com/nubcake94/pulsing_button"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter